defmodule Elixirbits.Repo.Migrations.AddAccessControlTablesAndProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :roles, {:array, :text}, null: false, default: []
      add :username, :text
      add :display_name, :text
      add :display_pic_url, :text
      add :display_pic_name, :text
      add :first_name, :text
      add :middle_name, :text
      add :last_name, :text
      add :tel_no, :text
      add :weight_kg, :decimal
      add :height_cm, :decimal
      add :dob, :utc_datetime
      add :sex, :text
      add :locale, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:sitenav_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:sitenav, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:sitenav_versions) do
      modify :version_source_id,
             references(:sitenav,
               column: :id,
               name: "sitenav_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sitenav) do
      add :code, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :level, :bigint, null: false
      add :parent, :text
      add :url, :text
      add :sequence, :bigint
      add :state, :text, null: false, default: "ENABLED"
      add :roles_bypass, {:array, :text}, null: false, default: []
      add :users_bypass, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:sitenav, [:code], name: "sitenav_unique_code_index")

    create table(:roles_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:roles_versions) do
      modify :version_source_id,
             references(:roles,
               column: :id,
               name: "roles_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:roles) do
      add :code, :text, null: false
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:roles, [:code], name: "roles_unique_code_index")

    create table(:role_perms_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:role_perms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:role_perms_versions) do
      modify :version_source_id,
             references(:role_perms,
               column: :id,
               name: "role_perms_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:role_perms) do
      add :level, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sitenav_code,
          references(:sitenav,
            column: :code,
            name: "role_perms_sitenav_code_fkey",
            type: :text,
            prefix: "public",
            on_delete: :restrict,
            on_update: :update_all
          ),
          null: false

      add :roles_code,
          references(:roles,
            column: :code,
            name: "role_perms_roles_code_fkey",
            type: :text,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:role_perms, [:roles_code, :sitenav_code],
             name: "role_perms_unique_role_sitenav_index"
           )

    create index(:role_perms, [:sitenav_code])

    create index(:role_perms, [:roles_code])

    alter table(:ledger_balances) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:api_keys) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:addresses_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:addresses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuidv7()"), primary_key: true
    end

    alter table(:addresses_versions) do
      modify :version_source_id,
             references(:addresses,
               column: :id,
               name: "addresses_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:addresses) do
      add :contact_name, :text
      add :contact_tel_no, :text
      add :country, :text
      add :line_1, :text
      add :line_2, :text
      add :line_3, :text
      add :postal_code, :text
      add :city, :text
      add :state, :text
      add :latitudde, :decimal
      add :longitude, :decimal
      add :label, :text
      add :other_label, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "addresses_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create index(:addresses, [:user_id])
  end

  def down do
    drop_if_exists index(:addresses, [:user_id])

    drop constraint(:addresses, "addresses_user_id_fkey")

    alter table(:addresses) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :other_label
      remove :label
      remove :longitude
      remove :latitudde
      remove :state
      remove :city
      remove :postal_code
      remove :line_3
      remove :line_2
      remove :line_1
      remove :country
      remove :contact_tel_no
      remove :contact_name
    end

    drop constraint(:addresses_versions, "addresses_versions_version_source_id_fkey")

    alter table(:addresses_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:addresses)

    drop table(:addresses_versions)

    alter table(:api_keys) do
      remove :updated_at
      remove :inserted_at
    end

    alter table(:ledger_balances) do
      remove :updated_at
      remove :inserted_at
    end

    drop_if_exists index(:role_perms, [:roles_code])

    drop_if_exists index(:role_perms, [:sitenav_code])

    drop constraint(:role_perms, "role_perms_sitenav_code_fkey")

    drop constraint(:role_perms, "role_perms_roles_code_fkey")

    drop_if_exists unique_index(:role_perms, [:roles_code, :sitenav_code],
                     name: "role_perms_unique_role_sitenav_index"
                   )

    alter table(:role_perms) do
      remove :roles_code
      remove :sitenav_code
      remove :updated_at
      remove :inserted_at
      remove :level
    end

    drop constraint(:role_perms_versions, "role_perms_versions_version_source_id_fkey")

    alter table(:role_perms_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:role_perms)

    drop table(:role_perms_versions)

    drop_if_exists unique_index(:roles, [:code], name: "roles_unique_code_index")

    alter table(:roles) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
      remove :code
    end

    drop constraint(:roles_versions, "roles_versions_version_source_id_fkey")

    alter table(:roles_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:roles)

    drop table(:roles_versions)

    drop_if_exists unique_index(:sitenav, [:code], name: "sitenav_unique_code_index")

    alter table(:sitenav) do
      remove :updated_at
      remove :inserted_at
      remove :users_bypass
      remove :roles_bypass
      remove :state
      remove :sequence
      remove :url
      remove :parent
      remove :level
      remove :description
      remove :name
      remove :code
    end

    drop constraint(:sitenav_versions, "sitenav_versions_version_source_id_fkey")

    alter table(:sitenav_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:sitenav)

    drop table(:sitenav_versions)

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :locale
      remove :sex
      remove :dob
      remove :height_cm
      remove :weight_kg
      remove :tel_no
      remove :last_name
      remove :middle_name
      remove :first_name
      remove :display_pic_name
      remove :display_pic_url
      remove :display_name
      remove :username
      remove :roles
    end
  end
end
