defmodule ElixirbitsWeb.Admin.LayoutTestLive do
  use ElixirbitsWeb, :live_view

  alias LiveSelect.Component

  @dependency_pages [
    %{
      id: "sign-in",
      name: "Sign In",
      source: "AshAuthentication",
      path: "/sign-in",
      availability: "always",
      description: "Password and magic-link entry flow."
    },
    %{
      id: "register",
      name: "Register",
      source: "AshAuthentication",
      path: "/register",
      availability: "always",
      description: "User registration screen generated by dependency overrides."
    },
    %{
      id: "reset",
      name: "Reset Password",
      source: "AshAuthentication",
      path: "/reset",
      availability: "always",
      description: "Password reset request and token flow."
    },
    %{
      id: "swagger",
      name: "Swagger UI",
      source: "OpenApiSpex",
      path: "/api/json/swaggerui",
      availability: "always",
      description: "JSON API explorer and schema browser."
    },
    %{
      id: "dashboard",
      name: "Live Dashboard",
      source: "Phoenix LiveDashboard",
      path: "/dev/dashboard",
      availability: "dev only",
      description: "Runtime metrics, request log, processes, sockets."
    },
    %{
      id: "mailbox",
      name: "Mailbox Preview",
      source: "Swoosh",
      path: "/dev/mailbox",
      availability: "dev only",
      description: "Inspect local and test emails from browser."
    },
    %{
      id: "ash-admin",
      name: "Ash Admin",
      source: "AshAdmin",
      path: "/admin",
      availability: "dev only",
      description: "Generated admin UI for resources and actions."
    }
  ]

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign(:current_scope, nil)
     |> assign(:current_tab, "local")
     |> assign(:ash_auth_overrides, [
       ElixirbitsWeb.AuthOverrides,
       Elixir.AshAuthentication.Phoenix.Overrides.DaisyUI
     ])
     |> assign(:dependency_form, to_form(%{}, as: :dependency))
     |> assign(:dependency_pages, @dependency_pages)
     |> assign(
       :local_form,
       to_form(
         %{
           "hidden_token" => "LT-LOCAL",
           "project_name" => "Layout Test",
           "email" => "builder@elixirbits.dev",
           "password" => "password123",
           "budget" => "24000",
           "launch_date" => "2026-04-23",
           "launch_time" => "09:30",
           "launch_week" => "2026-W17",
           "launch_month" => "2026-04",
           "launch_at" => "2026-04-23T09:30",
           "accent" => "#c9822b",
           "search" => "flash button",
           "website" => "https://phoenixframework.org",
           "phone" => "+60 123456789",
           "notes" => "Core components, layout flow, dependency surfaces.",
           "role" => "admin",
           "enabled" => true
         },
         as: :local
       )
     )
     |> assign(:page_title, "Layout Test")
     |> assign(:sitenav_query, Ash.Query.sort(Elixirbits.AccessControl.Sitenav, sequence: :asc))
     |> assign(:selected_dependency, nil)}
  end

  @impl true
  def handle_event("change_tab", %{"tab" => tab}, socket) do
    {:noreply,
     assign(
       socket,
       :current_tab,
       if(tab in ["local", "ecosystem"], do: tab, else: socket.assigns.current_tab)
     )}
  end

  @impl true
  def handle_event("show_flash", %{"kind" => "info"}, socket) do
    {:noreply, put_flash(socket, :info, "Layout test info flash is alive.")}
  end

  @impl true
  def handle_event("show_flash", %{"kind" => "error"}, socket) do
    {:noreply, put_flash(socket, :error, "Layout test error flash is alive.")}
  end

  @impl true
  def handle_event("show_flash", _params, socket), do: {:noreply, socket}

  @impl true
  def handle_event("dependency_change", params, socket) do
    dependency_params = Map.get(params, "dependency", %{})

    {:noreply,
     socket
     |> assign(:dependency_form, to_form(dependency_params, as: :dependency))
     |> assign(
       :selected_dependency,
       case Map.get(dependency_params, "component_search") do
         nil ->
           nil

         "" ->
           nil

         path ->
           Enum.find(@dependency_pages, &(&1.path == path))
       end
     )}
  end

  @impl true
  def handle_event("live_select_change", %{"id" => id} = params, socket) do
    text = Map.get(params, "text", "") |> String.downcase()

    options =
      @dependency_pages
      |> Enum.filter(fn page ->
        text == "" or
          String.contains?(String.downcase(page.name), text) or
          String.contains?(String.downcase(page.source), text) or
          String.contains?(String.downcase(page.path), text)
      end)
      |> Enum.map(fn page -> {"#{page.name} (#{page.source})", page.path} end)

    send_update(Component, id: id, options: options)

    {:noreply, socket}
  end
end
